### ISSUE TITLE
resources extensions only apply to the first function

### ISSUE THREAD

**Issue by spencer-grimes-mAx** [serverless-operations/serverless-step-functions#372]
# Using Resources from AWS only applying to first lambda function in the step function

## I'm trying  to leverage FileSystemConfigs properties of AWS in order to share large python libraries 
I'm using AWS Lambdas in my step function. I'm trying to use resources extensions to leverage FileSystemConfigs properties of AWS in order to share large python libraries (pandas, requests, etc) between the lambdas in my step function. Adding the EFS this way works for the first lambda in the step function, but the other lambdas are not having the EFS resource set. 

I know everything else is working because when I add the EFS manually (in the AWS lambda console) the functions all run successfully. 

I've tried setting the resource yml properties in the function itself, as well as several levels within the default step function wide .yml file. 

Here's my current config: 

resources:
  extensions:
    # Name of function <hello>
    ## see https://www.serverless.com/framework/docs/providers/aws/guide/resources/#override-aws-cloudformation-resource for more details on what's going on here
    HelloLambdaFunction: ##todo, I don't understand what this name does
      Properties:
        FileSystemConfigs:
          - Arn: 'arn:aws:elasticfilesystem:${self:provider.region}:#{AWS::AccountId}:access-point/${self:custom.efsAccessPoint}'
            LocalMountPath: '${self:custom.LocalMountPath}'

**Comment by theburningmonk** [comment]
@spencer-grimes-mAx if you run `sls package`, the Serverless framework would generate the actual CloudFormation template that will be deployed, and if you inspect the `.serverless` folder you will see a `xxx-update.json` file. Have a look in there for the functions whose configurations you want to extend.

The `HelloLambdaFunction` is the "logical id" (basically the key for the resources in the CloudFormation template) of the resource that represents the Lambda function. The Serverless framework has a convention for how to name them - if you call your function `hello` in the `functions` section, then it'll generate a logical ID based on that and it'll be called `HelloLambdaFunction`. Unfortunately, that abstraction is kinda leaky when it comes to resource extensions...

So if you have functions
```
functions:
  hello:
     ...
  world:
     ...
```
and you want to extend their configurations to allow EFS then you'll need to override each of them in the resource extensions, e.g.
```
HelloLambdaFunction:
  ...
WorldLambdaFunction:
  ...
```
and the best way to figure out those names is to look in the `.serverless` folder and see what Serverless framework has named them.

I'm gonna close the issue since it's not related to the plugin itself, but feel free to continue the conversation nonetheless.
