### ISSUE TITLE
EventBridge Scheduler Integration for Stepfunction

### ISSUE THREAD

**Issue by jappurohit041** [serverless-operations/serverless-step-functions#571]
# Feature Proposal

For feature proposals:
-> Ability to create AWS::Scheduler::Schedule triggers as an alternative to AWS::Event::Rule, which may be preferable if hitting account-wide limits on a number of AWS::Event::Rule triggers per bus (Lambdas are only able to be triggered from the default bus).
-> Also, specify a timezone to run it on local time.

**Comment by jappurohit041** [comment]
Please follow the work for the same in following repository:
https://github.com/distinction-dev/serverless-step-functions/tree/feat-schedule-eventbridge

**Comment by ayhamdewan** [comment]
Is there any update on adding this feature?

**Comment by danmactough** [comment]
This is an essential enhancement to this plugin to maintain parity with Serverless. See https://github.com/serverless/serverless/pull/11935

@jappurohit041 @KillDozerX2 Can you make your PR to this repository so it can have a chance of getting merged and released?

**Comment by KillDozerX2** [comment]
> This is an essential enhancement to this plugin to maintain parity with Serverless. See [serverless/serverless#11935](https://github.com/serverless/serverless/pull/11935)
> 
> @jappurohit041 @KillDozerX2 Can you make your PR to this repository so it can have a chance of getting merged and released?

Yeah, getting there.

**Comment by KillDozerX2** [comment]
> This is an essential enhancement to this plugin to maintain parity with Serverless. See [serverless/serverless#11935](https://github.com/serverless/serverless/pull/11935)
> 
> @jappurohit041 @KillDozerX2 Can you make your PR to this repository so it can have a chance of getting merged and released?

Apologies for the delay, we've opened a new PR for this. #580

**Comment by jappurohit041** [comment]
Hii @horike37 @lopburny,

Could we please have look at this issue, as it has been opened since very long and we have PR ready to implement this?

Thanks

**Comment by jeffreydmohler** [comment]
Hi @KillDozerX2, @jappurohit041, @horike37

It seems like there is a key piece that was missed here. There is no way to pass input into the target.  There are no errors when an input is passed, but when deployed, it never gets set. 

Serverless allows for this functionality with Lambdas (see [here](https://www.serverless.com/framework/docs/providers/aws/events/schedule#use-awsschedulerschedule-instead-of-awseventrule))

Cloudformation also allows for this pretty simply (see [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-scheduler-schedule-target.html#cfn-scheduler-schedule-target-input))

I imagine this was just missed or overlooked when adding this new code (see [here](https://github.com/serverless-operations/serverless-step-functions/blob/master/lib/deploy/events/schedule/compileScheduledEvents.js#L156-L158)) because errors were added for InputPath and InputTransformer.

Can this issue be re-opened for this functionality to be added?
